; AxelF, AKG format, v1.0.

; Generated by Arkos Tracker 2.

AxelF_Start
AxelF_StartDisarkGenerateExternalLabel

AxelF_DisarkByteRegionStart0
	db "AT20"
AxelF_DisarkPointerRegionStart1
	dw AxelF_ArpeggioTable	; The address of the Arpeggio table.
	dw AxelF_PitchTable	; The address of the Pitch table.
	dw AxelF_InstrumentTable	; The address of the Instrument table.
	dw AxelF_EffectBlockTable	; The address of the Effect Block table.
AxelF_DisarkPointerRegionEnd1


; The addresses of each Subsong:
AxelF_DisarkPointerRegionStart2
	dw AxelF_Subsong0_Start
AxelF_DisarkPointerRegionEnd2

; Declares all the Arpeggios.
AxelF_ArpeggioTable
AxelF_DisarkPointerRegionStart3
AxelF_DisarkPointerRegionEnd3

; Declares all the Pitches.
AxelF_PitchTable
AxelF_DisarkPointerRegionStart4
AxelF_DisarkPointerRegionEnd4

; Declares all the Instruments.
AxelF_InstrumentTable
AxelF_DisarkPointerRegionStart5
	dw AxelF_EmptyInstrument
	dw AxelF_Instrument1
	dw AxelF_Instrument2
	dw AxelF_Instrument3
AxelF_DisarkPointerRegionEnd5

AxelF_EmptyInstrument
	db 0	; The speed (>0, 0 for 256).
AxelF_EmptyInstrument_Loop	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

AxelF_Instrument1
	db 3	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 6	; Loop to silence.

AxelF_Instrument2
	db 15	; The speed (>0, 0 for 256).
	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 145	; Soft only. Volume: 2. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 6	; Loop to silence.

AxelF_Instrument3
	db 3	; The speed (>0, 0 for 256).
	db 121	; Soft only. Volume: 15.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 6	; Loop to silence.


; The indexes of the effect blocks used by this song.
AxelF_EffectBlockTable
AxelF_DisarkPointerRegionStart6
	dw AxelF_EffectBlock_P14P176P246	; Index 0
AxelF_DisarkPointerRegionEnd6

AxelF_EffectBlock_P14P176P246
	db 14, 176, 246

AxelF_DisarkByteRegionEnd0

; Subsong 0
; ----------------------
AxelF_Subsong0_DisarkByteRegionStart0
AxelF_Subsong0_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 0	; End index (>=0).
	db 9	; Initial speed (>=0).
	db 10	; Base note index (>=0).

AxelF_Subsong0_Linker
AxelF_Subsong0_DisarkPointerRegionStart1
; Position 0
AxelF_Subsong0_Linker_Loop
	dw AxelF_Subsong0_Track0
	dw AxelF_Subsong0_Track1
	dw AxelF_Subsong0_Track2
	dw AxelF_Subsong0_LinkerBlock0

AxelF_Subsong0_DisarkPointerRegionEnd1
	dw 0	; Loop.
AxelF_Subsong0_DisarkWordForceReference2
	dw AxelF_Subsong0_Linker_Loop

AxelF_Subsong0_LinkerBlock0
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
AxelF_Subsong0_DisarkWordForceReference3
	dw AxelF_Subsong0_SpeedTrack0	; SpeedTrack address.
AxelF_Subsong0_DisarkWordForceReference4
	dw AxelF_Subsong0_EventTrack0	; EventTrack address.

AxelF_Subsong0_Track0
	db 171
	db 3	; New Instrument (3).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 174
	db 1	; New Instrument (1).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 171
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 171
	db 1	; New Instrument (1).
	db 48
	db 60	; Waits for 1 line.

	db 171
	db 3	; New Instrument (3).
	db 60	; Waits for 1 line.

	db 169
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 171
	db 3	; New Instrument (3).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 178
	db 1	; New Instrument (1).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 43
	db 60	; Waits for 1 line.

	db 43
	db 51
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 46
	db 60	; Waits for 1 line.

	db 43
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 55
	db 60	; Waits for 1 line.

	db 43
	db 41
	db 60	; Waits for 1 line.

	db 41
	db 38
	db 60	; Waits for 1 line.

	db 45
	db 60	; Waits for 1 line.

	db 43
	db 61, 5	; Waits for 6 lines.

	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


AxelF_Subsong0_Track1
	db 60	; Waits for 1 line.

	db 128
	db 0	; New Instrument (0).
	db 61, 48	; Waits for 49 lines.

	db 172
	db 2	; New Instrument (2).
	db 61, 127	; Waits for 128 lines.


AxelF_Subsong0_Track2
	db 61, 127	; Waits for 128 lines.


; The speed tracks
AxelF_Subsong0_SpeedTrack0
	db 255	; Wait for 128 lines.

; The event tracks
AxelF_Subsong0_EventTrack0
	db 255	; Wait for 128 lines.

AxelF_Subsong0_DisarkByteRegionEnd0
